### ISSUE TITLE
Error Message: "Notepad== is damaged and can't be opened. You should move it to the Trash"

### ISSUE THREAD

**Issue by SchnauzerLogic** [matthewyang204/NotepadEE#1]
Download the latest 3.1.0 package for Arm64 (Mac Mini M2Pro) but see this error message upon launch.
<img width="332" alt="Screenshot 2024-07-07 at 1 16 51 PM" src="https://github.com/matthewyang204/NotepadEE/assets/82987167/d02188f1-0f17-4d46-b7e1-8e0b2c93bdbf">

**Comment by matthewyang204** [comment]
Um, you need to type 'xattr -d com.apple.quarantine ' and then drag the app into the terminal, pressing enter. Let me know if that solved it. Sorry, but my binaries are not signed, and I can't really afford an Apple Developer paid account right now.
